services:
  - type: web
    name: hydrotech-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: OPENWEATHER_API_KEY
        sync: false  # Set this in Render dashboard
